channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - astrometry
  - fastapi
  - h5py
  - matplotlib-base
  - numexpr
  - numpy
  - pandas
  - photutils
  - pip
  - pyarrow
  - scikit-learn
  - scipy
  - seaborn
  - uvicorn
  - watchfiles
  - pip:
      - panoptes-utils[config,images,social]
      - panoptes-data
