channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astropy
  - astrometry
  - fastapi
  - matplotlib-base
  - numexpr
  - numpy
  - pandas
  - photutils
  - pip
  - scipy
  - uvicorn
  - watchfiles
  - pip:
      - panoptes-utils[config,images,social]
